### ISSUE TITLE
Internal server error while handling `POST /data_object/workflow_summary` request

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/nmdc-server#1415]
I'm seeing locally and on dev that there is an exception being consistently thrown while handling a `POST /data_object/workflow_summary` request. The stack trace is:

```
  ERROR:    Exception in ASGI application
  Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/sessions.py", line 77, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/app/./nmdc_server/api.py", line 536, in data_object_aggregation
    return crud.aggregate_data_object_by_workflow(db, query.conditions)
  File "/app/./nmdc_server/crud.py", line 335, in aggregate_data_object_by_workflow
    return aggregations.get_data_object_aggregation(db, conditions)
  File "/app/./nmdc_server/aggregations.py", line 209, in get_data_object_aggregation
    agg[row[0]].count = row[1]
KeyError: 'nmdc:MAGsAnalysisActivity'
```

**Comment by pkalita-lbl** [comment]
The cause of the error here is these three lines which are the last steps of the ingest: https://github.com/microbiomedata/nmdc-server/blob/fd8ff76e7f5d4cf58a076f498294f6f27451ec48/nmdc_server/jobs.py#L87-L89

Those lines merge objects from the live DB into the ingest DB _and_ they have relationships to `DataObject` instances. As the SQLAlchemy [docs](https://docs.sqlalchemy.org/en/14/orm/session_state_management.html#merging) about the `merge` method say:

> The operation is cascaded to related objects and collections

So even though the `data_object` table is truncated at the start of the ingest and populated with fresh data from MongoDB during the "primary" ingest operations, these final merges allow rows of `data_object` to be added/updated using "old" information from the live DB.

I think the path forward on this is to write a migration to rename the values in the `workflow_type` column of the `data_object` table and ensure that runs before migration.

**Comment by pkalita-lbl** [comment]
The commit where the enum values were changed: https://github.com/microbiomedata/nmdc-server/pull/1295/files#diff-ba534f7ac5fb77224ce924beb4b1edbe0e0a6da34fdc770f55bd2e253dc55fe3
