### ISSUE TITLE
Reads QC, Metagenome Assembly, Metagenome Annotation 500

### ISSUE THREAD

**Issue by subdavis** [microbiomedata/nmdc-server#59]
Same error as before.   cc @jbeezley 

I rebuilt and cleared existing docker volumes.  

```
curl -X POST "http://localhost:8080/api/reads_qc/search?limit=100" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"conditions\":[]}"
```

```
backend_1  | 172.21.0.4:49606 - "POST /api/reads_qc/search?limit=100 HTTP/1.0" 500
backend_1  | [2020-07-20 19:50:34 +0000] [31] [ERROR] Exception in ASGI application
backend_1  | Traceback (most recent call last):
backend_1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
backend_1  |     result = await app(self.scope, self.receive, self.send)
backend_1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
backend_1  |     return await self.app(scope, receive, send)
backend_1  |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 181, in __call__
backend_1  |     await super().__call__(scope, receive, send)
backend_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 102, in __call__
backend_1  |     await self.middleware_stack(scope, receive, send)
backend_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
backend_1  |     raise exc from None
backend_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
backend_1  |     await self.app(scope, receive, _send)
backend_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
backend_1  |     raise exc from None
backend_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
backend_1  |     await self.app(scope, receive, sender)
backend_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 550, in __call__
backend_1  |     await route.handle(scope, receive, send)
backend_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
backend_1  |     await self.app(scope, receive, send)
backend_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
backend_1  |     response = await func(request)
backend_1  |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 204, in app
backend_1  |     response_data = await serialize_response(
backend_1  |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 125, in serialize_response
backend_1  |     raise ValidationError(errors, field.type_)
backend_1  | pydantic.error_wrappers.ValidationError: 100 validation errors for ReadsQCSearchResponse

```

**Comment by jbeezley** [comment]
Okay, I clearly need to some integration tests with the actual data.  Should be an easy fix.
